language: python

sudo: false

env:
  global:
    - secure: "i/Uj39kBUz9zrzUY86OUkAe8zrKlKijuVzADqdlV8YCgiCuuP/d7ZUlS13SSXRXeiSlDAUSta4wqFkmLL/EfdIiLRRAooM12D1xMEozL/suoi3wS8B2WTZ0J4On5u5na6sCtI/9YqjlZ3RzKfPl3j11ye0VldLR6Rdf/VQpW80+QpqCeiEmBzbUeRHWOiOTT7Joo4dGwgnBlUtYWmTC4nAydrMuko0cznueKf7x2dGBpcBoFF9ylZP08V1vH2Y7OC6Nd/oEKS8MoKstXUNk0QamVEXeZejjska/7odyCt9uWOCdCN594H6G7ECbQz5UvlUiOWL/jb9UsIhosvKMLGt5lg50LAMZphMq/FARU/oA+gIf3m5EvOODFNvDK7/3OJXrVkD07fkFDhe99mo4/hgiadkQVx0RIXIRcG2vO9LbyOBux2ASjYR7clv0q7Rj6zckt3L/knU8tXOQbW2VSx2czQFFNIC1EFP6h5ydK0s/bRMWO23xOToxdRlyFYn5HVwYpxPGFvFywjyWm4lkCBvb1s4UuriWe4ikVTyNdukchpwLaP9Uz02I5pVPkKdkiv3SGS+jjCoQdGSnOmk13ruqszUxgfb5BSkD0ACrGos4O0NG/8TDXuxf8nKS1bwATIIwAp0cCYgIxolODFU79YS6hSOHr2RJxdlwl9bQVykk="

matrix:
  fast_finish: true
  include:
  - python: 3.5
    env: TEST_TARGET=default NUMPY=1.11
  - python: 3.5
    env: TEST_TARGET=default NUMPY=1.12
  - python: 3.6
    env: TEST_TARGET=default NUMPY=1.11
  - python: 3.6
    env: TEST_TARGET=default NUMPY=1.12
  - python: 3.6
    env: TEST_TARGET=publish NUMPY=1.12
  allow_failures:
  - python: 3.6
    env: TEST_TARGET=publish NUMPY=1.12

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update conda --yes
    - conda config --add channels conda-forge --force
    - conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements-dev.txt
    - source activate TEST
    # Install after to ensure it will be downgraded when testing an older version.
    - conda install --yes --quiet numpy=$NUMPY
# Test source distribution.
install:
    - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install gsw-${version}.tar.gz && popd

script:
    - if [[ $TEST_TARGET == "default" ]]; then
        pushd gsw && py.test -s -rxs -v tests && popd ;
      fi

after_success:
    - if [[ $TEST_TARGET == "publish" ]]; then
        set -e ;
        pip install sphinx_rtd_theme ;
        pip install doctr ;
        pushd docs && make html && popd ;
        doctr deploy --built-docs=docs/_build/html . ;
      fi
