name: Test code generation

on:
  pull_request:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  code-generation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c   # v6.0.0
      with:
        python-version: "3.x"

    - name: Install gsw
      run: >
        python -m pip install -r requirements-dev.txt
        && python -m pip install -e .

    - name: Test Code Generation
      run: >
        git clone https://github.com/TEOS-10/GSW-C.git ../GSW-C
        && git clone https://github.com/TEOS-10/GSW-Matlab.git ../GSW-Matlab
        && python tools/copy_from_GSW-C.py
        && python tools/mat2npz.py
        && python tools/make_ufuncs.py
        && python tools/make_wrapped_ufuncs.py
        && python tools/fix_wrapped_ufunc_typos.py

    - name: Install gsw
      run: >
        python -m pip install -v -e  . --no-deps --no-build-isolation --force-reinstall
        && python -m pytest -s -rxs -v gsw/tests
    permissions:
      actions: none